<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MVC Project</title>
        <link href="/app/views/style.css" rel="stylesheet">
    </head>

    <body>
        <header class="header">
            <div class="container header-content">
                <div class="logo item_style">
                    MVC "Project"
                </div>
                <nav>
                    <ul class="header-navigation item_style">
                        <li class="header-navigation_item">
                            <a href="http:/home">HOME</a>
                        </li>
                        <li class="header-navigation_item">
                            <a href="http:/home/airmodals">PROJECTS AIR</a>
                        </li>
                        <li class="header-navigation_item">
                            <a href="http:/home/news">NEWS</a>
                        </li>
                        <li class="header-navigation_item">
                            <a href="http:/home/specialAviation">SPECIAL AVIATION</a>
                        </li>
                        <li class="header-navigation_item">
                            <a href="http:/home/contacts">CONTACTS</a>
                        </li>
                        <li class="header-navigation_item">
                            <a href="#">REVIEWS</a>
                        </li>
                    </ul>
                </nav>

            </div>
        </header>
        <main>
            <section class="turnkey">
                <div class="container container-turnkey">
                    <div class="indent">
                        <h1 class="title">
                            United Aircraft Corporation
                            <span>UAC</span>
                        </h1>
                        <p>Объединенная авиастроительная корпорация (ОАК) создана в 2006 году с целью
                            консолидации крупнейших самолетостроительных активов России. Входящие в
                            корпорацию предприятия выпускают самолеты таких всемирно известных брендов как
                            «Су», «МиГ», «Ил», «Ту», «Як», «Бериев», а также новые – Superjet 100 и МС-21.
                            Предприятия OAK выполняют все работы по созданию и поддержанию полного
                            жизненного цикла авиационной техники.
                        </p>

                    </div>
                    <?php include_once VIEW . $content_view; ?>
                </div>

            </div>

        </section>

    </main>

    <footer class="foot_header header hide_after">
        <div class="container header-content">
            <div class="logo item_style">
                MVC "Project"
            </div>
            <nav>
                <ul class="header-navigation item_style">
                    <li class="header-navigation_item">
                        <a href="#">HOME</a>
                    </li>
                    <li class="header-navigation_item">
                        <a href="#">PROJECTS</a>
                    </li>
                    <li class="header-navigation_item">
                        <a href="#">MEASUREMENT</a>
                    </li>
                    <li class="header-navigation_item">
                        <a href="#">TEAM</a>
                    </li>
                    <li class="header-navigation_item">
                        <a href="#">REVIEWS</a>
                    </li>
                    <li class="header-navigation_item">
                        <a href="#">CONTACTS</a>
                    </li>

                </footer>

            </body>

        </html>